
generateMatrix:generateMatrix.cpp
	g++ -g $^ -o $@
spiralOrder:spiralOrder.cpp
	g++ -g $^ -o $@
singleNumber:singleNumber.cpp
	g++ -g $^ -o $@
permute:permute.cpp
	g++ -g $^ -o $@
multiply:multiply.cpp
	g++ -g $^ -o $@

